services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: banners
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/banners?sslmode=disable"
      PORT: "3000"
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres_data: